### ISSUE TITLE
What is the licencing?

### ISSUE THREAD

**Issue by thomaskessler1** [georgik/pf2019#1]
I work for a small education company (learnign for humanity) and we are looking to possibly use your webapp in our system, what is the licencing?

**Comment by georgik** [comment]
Added MIT license. Feel free to use the software or modify it.
If you have any nice modifications, let me know. I'll be glad to put a link on them.
Graphical assets are from free sources under Creative Common License.

**Comment by thomaskessler1** [comment]
Thank you very much
